GET http://localhost:8080/
###
GET http://localhost:8080/product
###
GET http://localhost:8080/typeProduct
###
POST http://localhost:8080/product
Content-Type: application/json

{
    "name": "Cerveja Puro Malte",
    "typeProduct": {
        "id": 2
    },
    "price": 5.30,
    "desc": "Unidade",
    "model": "350ml Lata",
    "brand": "Becks",
    "quantity": 30
}
###
POST http://localhost:8080/typeProduct
Content-Type: application/json

{
    "name": "salagadinho/aperitivos"
}
###
###
GET http://localhost:8080/product/1
###
GET http://localhost:8080/typeProduct/1
###
PUT http://localhost:8080/product/5
Content-Type: application/json

{
    "name": "Cerveja Puro Malte",
    "typeProduct": {
        "id": 2
    },
    "price": 3.50,
    "desc": "Unidade",
    "model": "350ml Lata",
    "brand": "Becks",
    "quantity": 30
}
###
PUT http://localhost:8080/typeProduct/2
Content-Type: application/json

{
    "name": "Produtos para Casa"
}
###
DELETE http://localhost:8080/product/1
###
DELETE http://localhost:8080/typeProduct/3
###
POST http://localhost:8080/stockMovement
Content-Type: application/json

{
    "product": {
        "id": 4
    },
    "quantity": 50,
    "typeMovement": "INPUT"
}
###
GET http://localhost:8080/stockMovement
###
GET http://localhost:8080/stockMovement/2
###
DELETE http://localhost:8080/stockMovement/2


