GET http://localhost:8080/
###
GET http://localhost:8080/product
###
GET http://localhost:8080/typeProduct
###
POST http://localhost:8080/product
Content-Type: application/json

{
    "nome": "Cerveja Puro Malte",
    "typeProduct": {
        "id": 2
    },
    "preco": 5.30,
    "descricao": "Unidade",
    "modelo": "350ml Lata",
    "marca": "Becks",
    "quantidade": 30
}
###
POST http://localhost:8080/typeProduct
Content-Type: application/json

{
    "nome": "salagadinho/aperitivos"
}
###
###
GET http://localhost:8080/product/1
###
GET http://localhost:8080/typeProduct/1
###
PUT http://localhost:8080/product/5
Content-Type: application/json

{
    "nome": "Cerveja Puro Malte",
    "typeProduct": {
        "id": 2
    },
    "preco": 3.30,
    "descricao": "Unidade",
    "modelo": "350ml Lata",
    "marca": "Becks",
    "quantidade": 30
}
###
PUT http://localhost:8080/typeProduct/4
Content-Type: application/json

{
    "nome": "doces"
}
###
DELETE http://localhost:8080/product/1
###
DELETE http://localhost:8080/typeProduct/3
###
